# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
